### ISSUE TITLE
"TypeError: Reflect.ownKeys called on non-object" with null values

### ISSUE THREAD

**Issue by forivall** [duniul/sort-jsonc#1]
With the following file

`repro.json`
```jsonc
{
  // foo
  "value": null
}

```

and the command (installed via `npm i -g sort-jsonc-cli`)

`sort-jsonc repro.json`

i get the following output:

```
Type Error: Reflect.ownKeys called on non-object
    at Reflect.ownKeys (<anonymous>)
    at sortDeepWithSymbols (file:///opt/homebrew/lib/node_modules/sort-jsonc-cli/node_modules/sort-jsonc/dist/index.js:25:31)
    at sortJsonc (file:///opt/homebrew/lib/node_modules/sort-jsonc-cli/node_modules/sort-jsonc/dist/index.js:6:18)
    at file:///opt/homebrew/lib/node_modules/sort-jsonc-cli/dist/cli.js:39:35
    at async Promise.all (index 0)
    at async GenerateCommand.execute (file:///opt/homebrew/lib/node_modules/sort-jsonc-cli/dist/cli.js:35:26)
    at async GenerateCommand.validateAndExecute (/opt/homebrew/lib/node_modules/sort-jsonc-cli/node_modules/clipanion/lib/advanced/Command.js:73:26)
    at async Cli.run (/opt/homebrew/lib/node_modules/sort-jsonc-cli/node_modules/clipanion/lib/advanced/Cli.js:223:24)
    at async Cli.runExit (/opt/homebrew/lib/node_modules/sort-jsonc-cli/node_modules/clipanion/lib/advanced/Cli.js:232:28)
```

**Comment by duniul** [comment]
Hey @forivall and sorry for the super late response! I must have missed this in the notifications somehow.

The bug is fixed (see #4) and is included in [v1.0.1](https://github.com/duniul/sort-jsonc/releases/tag/sort-jsonc-cli%401.0.1)!
